# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'challan3.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QDialog, QApplication
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
import mysql.connector
from PyQt5.QtGui import *
#from main import *

lpno1=''
class Ui_Form3(object):
    def save(self, Form):
        global lpno1
        print("any"+lpno1+"hjh")
        off=self.comboBox_3.currentText()
        pen=self.lineEdit_2.text()
        place=self.lineEdit.text()
        mob=self.lineEdit_3.text()
        email=self.lineEdit_4.text()
        city=self.comboBox.currentText()
        state=self.comboBox_2.currentText()
        #sql="insert into plate(off,offplace,mno,email,offcity,offstate,pen) values("+off+","+place+","+mob+","+email+","+city+","+state+","+pen+")"
        cnx = mysql.connector.connect(user='root', password='',host='localhost',database='plates')
        conn=cnx.cursor()
        conn.execute("UPDATE `plate` SET `mno`='"+mob+"',`email`='"+email+"',`offstate`='"+state+"',`offcity`='"+city+"',`offplace`='"+place+"',`off`='"+off+"',`pen`='"+pen+"' WHERE lpno='"+lpno1+"'")
        #wn.show()
        wn3.hide()
        print("atlast")

    def setupUi3(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 793)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1061, 791))
        self.frame.setStyleSheet("background-color: #3366CC;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(80, 80, 891, 631))
        self.frame_2.setStyleSheet("background-color: white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(110, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(210, 210, 221, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(350, 30, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(140, 209, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(150, 279, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(140, 349, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(210, 280, 221, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 350, 221, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_3.setGeometry(QtCore.QRect(210, 80, 221, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 139, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 140, 221, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(630, 141, 221, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(480, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(630, 280, 221, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(490, 279, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(630, 210, 221, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 350, 221, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 440, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Offences"))
        self.label_2.setText(_translate("Form", "Complain Challan"))
        self.label_3.setText(_translate("Form", "Place"))
        self.label_4.setText(_translate("Form", "City"))
        self.label_5.setText(_translate("Form", "State"))
        self.comboBox.setItemText(0, _translate("Form", "Choose City"))
        self.comboBox_2.setItemText(0, _translate("Form", "Choose State"))
        self.comboBox_3.setItemText(0, _translate("Form", "Commercial Vehicles"))
        self.comboBox_3.setItemText(1, _translate("Form", "Driving"))
        self.comboBox_3.setItemText(2, _translate("Form", "Documents"))
        self.comboBox_3.setItemText(3, _translate("Form", "Horn"))
        self.comboBox_3.setItemText(4, _translate("Form", "Motor Vehicles"))
        self.comboBox_3.setItemText(5, _translate("Form", "Parking"))
        self.comboBox_3.setItemText(6, _translate("Form", "Pollution"))
        self.comboBox_3.setItemText(7, _translate("Form", "Road Marking"))
        self.comboBox_3.setItemText(8, _translate("Form", "Traffic Police"))
        self.comboBox_3.setItemText(9, _translate("Form", "Towing of Automobiles"))
        self.comboBox_3.setItemText(10, _translate("Form", "Traffic Signal"))
        self.comboBox_3.setItemText(11, _translate("Form", "Speed & Overtaking"))
        self.comboBox_3.setItemText(12, _translate("Form", "Vehicle Number Plates"))
        self.comboBox_3.setItemText(13, _translate("Form", "Vehicle Lights"))
        self.label_6.setText(_translate("Form", "Penalty/ Sentence"))
        self.label_7.setText(_translate("Form", "Mobile Number"))
        self.label_8.setText(_translate("Form", "Email Address"))
        self.pushButton.setText(_translate("Form", "Send SMS"))
        self.pushButton_2.setText(_translate("Form", "Send Email"))
        self.pushButton_3.setText(_translate("Form", "Submit"))
        self.pushButton_3.clicked.connect(self.save)

class AppWindow4(QDialog,QApplication):
    def __init__(self,parent=None):
        super().__init__(parent)
        self.ui = Ui_Form3()
        self.ui.setupUi3(self)
    def setplno(self,pno):
        global lpno1
        lpno1=pno
        #print(pno+lpno1)
        
        
app = QApplication(sys.argv)
wn3 = AppWindow4()
'''wn3.show()
sys.exit(app.exec_())       
this is removed one runing as whole and show'''



